set(SOURCE_FILES
  Source/Application.cpp
  Source/Application.h
  Source/Window.cpp
  Source/Window.h
  Source/Events.h
  Source/Layer.cpp
  Source/Layer.h
  Source/Render/Render.cpp
  Source/Render/Render.h
  Source/Render/VulkanInstance.cpp
  Source/Render/VulkanInstance.h
  Source/Render/VulkanDebugExtension.cpp
  Source/Render/VulkanDebugExtension.h
  Source/Render/RenderSpecs.h
  Source/Render/VulkanPhysicalDevice.cpp
  Source/Render/VulkanPhysicalDevice.h
  Source/Render/VulkanDevice.cpp
  Source/Render/VulkanDevice.h
  Source/Render/VulkanSurface.cpp
  Source/Render/VulkanSurface.h
  Source/Render/VulkanSwapchain.cpp
  Source/Render/VulkanSwapchain.h
  Source/Render/VulkanPipeline.cpp
  Source/Render/VulkanPipeline.h
  Source/Render/VulkanRenderPass.cpp
  Source/Render/VulkanRenderPass.h
  Source/Render/VulkanCommandBuffer.cpp
  Source/Render/VulkanCommandBuffer.h
  Source/Render/VulkanSync.cpp
  Source/Render/VulkanSync.h
  Source/Render/VulkanVertexBuffer.cpp
  Source/Render/VulkanVertexBuffer.h
  Source/Render/VulkanMemoryAllocator.cpp
  Source/Render/VulkanMemoryAllocator.h
  Source/Render/VulkanDescriptorPool.cpp
  Source/Render/VulkanDescriptorPool.h
  Source/Render/PerFrameData.h
  Source/Render/PerFrameData.cpp
  Source/Render/VulkanDescriptorSet.cpp
  Source/Render/VulkanDescriptorSet.h
  Source/Render/VulkanUniformBuffer.cpp
  Source/Render/VulkanUniformBuffer.h
  Source/Render/VulkanTexture.cpp
  Source/Render/VulkanTexture.h
  Source/Render/VulkanMaterial.cpp
  Source/Render/VulkanMaterial.h
  Source/Scene/Scene.cpp
  Source/Scene/Scene.h
  Source/Assets/AssetManager.cpp
  Source/Assets/AssetManager.h
  Source/Assets/MeshManager.cpp
  Source/Assets/MeshManager.h
  Source/Assets/AssetManagerBase.h
  Source/Assets/AssetManager.cpp
  Source/Assets/AssetManager.h
  Source/Utils/Random.h
  Source/Assets/TextureManager.cpp
  Source/Assets/TextureManager.h
  Source/Assets/MaterialManager.cpp
  Source/Assets/MaterialManager.h
  Source/Scene/Components.h
  Source/FreeCamLayer.h
  Source/FreeCamLayer.cpp
  Source/Utils/Timer.h
  Source/Assets/ModelManager.cpp
  Source/Assets/ModelManager.h
  Source/EventBus.h
)
