set(SOURCE_FILES
  Source/Engine.cpp
  Source/Engine.h
  Source/Window.cpp
  Source/Window.h
  Source/Events.h
  Source/Layer.cpp
  Source/Layer.h
  Source/Render/Render.cpp
  Source/Render/Render.h
  Source/Render/VulkanInstance.cpp
  Source/Render/VulkanInstance.h
  Source/Render/VulkanDebugExtension.cpp
  Source/Render/VulkanDebugExtension.h
  Source/Render/RenderSpecs.h
  Source/Render/VulkanPhysicalDevice.cpp
  Source/Render/VulkanPhysicalDevice.h
  Source/Render/VulkanDevice.cpp
  Source/Render/VulkanDevice.h
  Source/Render/VulkanSurface.cpp
  Source/Render/VulkanSurface.h
  Source/Render/VulkanSwapchain.cpp
  Source/Render/VulkanSwapchain.h
  Source/Render/VulkanPipeline.cpp
  Source/Render/VulkanPipeline.h
  Source/Render/VulkanCommandBuffer.cpp
  Source/Render/VulkanCommandBuffer.h
  Source/Render/VulkanSync.cpp
  Source/Render/VulkanSync.h
  Source/Render/VulkanVertexBuffer.cpp
  Source/Render/VulkanVertexBuffer.h
  Source/Render/VulkanMemoryAllocator.cpp
  Source/Render/VulkanMemoryAllocator.h
  Source/Render/VulkanDescriptorPool.cpp
  Source/Render/VulkanDescriptorPool.h
  Source/Render/FrameUniformBuffer.h
  Source/Render/FrameUniformBuffer.cpp
  Source/Render/VulkanDescriptorSet.cpp
  Source/Render/VulkanDescriptorSet.h
  Source/Render/VulkanUniformBuffer.cpp
  Source/Render/VulkanUniformBuffer.h
  Source/Render/VulkanTexture.cpp
  Source/Render/VulkanTexture.h
  Source/Render/VulkanMaterial.cpp
  Source/Render/VulkanMaterial.h
  Source/Scene/Scene.cpp
  Source/Scene/Scene.h
  Source/Scene/TransformSystem.cpp
  Source/Scene/TransformSystem.h
  Source/Scene/ISystem.h
  Source/Scene/SystemScheduler.cpp
  Source/Scene/SystemScheduler.h
  Source/Scene/BoundsUpdateSystem.cpp
  Source/Scene/BoundsUpdateSystem.h
  Source/Assets/AssetManager.cpp
  Source/Assets/AssetManager.h
  Source/Assets/MeshManager.cpp
  Source/Assets/MeshManager.h
  Source/Assets/AssetManagerBase.h
  Source/Assets/IAssetManager.h
  Source/Assets/Handle.h
  Source/Assets/SlotMap.h
  Source/Utils/Random.h
  Source/Assets/TextureManager.cpp
  Source/Assets/TextureManager.h
  Source/Assets/MaterialManager.cpp
  Source/Assets/MaterialManager.h
  Source/Scene/Components.h
  Source/Utils/Timer.h
  Source/Assets/ModelDescription.h
  Source/Assets/ModelImporter.cpp
  Source/Assets/ModelImporter.h
  Source/Assets/ModelBuilder.cpp
  Source/Assets/ModelBuilder.h
  Source/Assets/ModelManager.cpp
  Source/Assets/ModelManager.h
  Source/Log.h
  Source/KeyCodes.h
  Source/InputActionSystem.h
  Source/InputActionSystem.cpp
  Source/ServiceRegistry.h
  Source/LayerManager.h
  Source/InputSystem.cpp
  Source/InputSystem.h
  Source/Render/VulkanImGui.cpp
  Source/Render/VulkanImGui.h
  Vendor/ImGui/imgui_impl_glfw.cpp
  Vendor/ImGui/imgui_impl_vulkan.cpp
  Source/Render/VulkanCubicTexture.cpp
  Source/Render/VulkanCubicTexture.h
  Source/Assets/CubeMapManager.cpp
  Source/Assets/CubeMapManager.h
  Source/Render/SkyBox.cpp
  Source/Render/SkyBox.h
  Source/Utils/Utils.h
  Source/Render/VulkanStorageBuffer.cpp
  Source/Render/VulkanStorageBuffer.h
  Source/Render/FrameContext.h
  Source/Render/RenderContext.h
  Source/Render/ImageBarrier.h
  Source/Render/VulkanBuffer.cpp
  Source/Render/VulkanBuffer.h
  Source/Render/VulkanImage.cpp
  Source/Render/VulkanImage.h
  Source/Render/RenderBackend.cpp
  Source/Render/RenderBackend.h
  Source/Render/DescriptorLayoutCache.cpp
  Source/Render/DescriptorLayoutCache.h
  Source/Render/RenderGraph.cpp
  Source/Render/RenderGraph.h
  Source/Render/VulkanComputePipeline.cpp
  Source/Render/VulkanComputePipeline.h
)

if(YA_EDITOR)
  list(APPEND SOURCE_FILES
    Source/Editor/EditorLayer.cpp
    Source/Editor/EditorLayer.h
    Source/Editor/IEditorPanel.h
    Source/Editor/EditorContext.h
    Source/Editor/Utils/EditorStyle.cpp
    Source/Editor/Utils/EditorStyle.h
    Source/Editor/Panels/ViewportPanel.h
    Source/Editor/Panels/PerformancePanel.h
    Source/Editor/Panels/PerformancePanel.cpp
    Source/Editor/Panels/RenderSettingsPanel.h
    Source/Editor/Panels/RenderSettingsPanel.cpp
    Source/Editor/Panels/OutlinerPanel.h
    Source/Editor/Panels/OutlinerPanel.cpp
    Source/Editor/Panels/DetailsPanel.h
    Source/Editor/Panels/DetailsPanel.cpp
    Source/Editor/Panels/MaterialBrowserPanel.h
    Source/Editor/Panels/MaterialBrowserPanel.cpp
    Source/Editor/Panels/MaterialInspectorPanel.h
    Source/Editor/Panels/MaterialInspectorPanel.cpp
    Source/Editor/Utils/EditorTextureCache.h
    Source/Editor/Utils/EditorTextureCache.cpp
    Source/Editor/Utils/FileDialog.h
    Source/Editor/Utils/FileDialog.cpp
    Source/Editor/EditorCameraLayer.h
    Source/Editor/EditorCameraLayer.cpp
  )
endif()
