"""Generates the editor icon header from a Lucide icon font release.

Usage: python Tools/generate_editor_icons.py <lucide-font dir> <lucide version> [output header]

<lucide-font dir> is the extracted `lucide-font` folder of lucide-font-<version>.zip from
https://github.com/lucide-icons/lucide/releases. It must contain codepoints.json and lucide.ttf.
The output defaults to Core/Source/Editor/Utils/EditorIcons.h. Copy the same lucide.ttf to
Core/Assets/Fonts so the header and the font never disagree.
"""

import json
import re
import struct
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "Core" / "Source" / "Editor" / "Utils" / "EditorIcons.h"


def read_cmap(font_path):
    """Codepoints the font actually maps: codepoints.json also lists brand icons the font omits."""
    data = font_path.read_bytes()
    table_count = struct.unpack(">H", data[4:6])[0]
    cmap_offset = None
    for i in range(table_count):
        tag, _, offset, _ = struct.unpack(">4sIII", data[12 + 16 * i:28 + 16 * i])
        if tag == b"cmap":
            cmap_offset = offset
    if cmap_offset is None:
        raise SystemExit(f"{font_path}: no cmap table")

    codepoints = set()
    subtable_count = struct.unpack(">H", data[cmap_offset + 2:cmap_offset + 4])[0]
    for i in range(subtable_count):
        record = cmap_offset + 4 + 8 * i
        _, _, sub_offset = struct.unpack(">HHI", data[record:record + 8])
        sub = cmap_offset + sub_offset
        fmt = struct.unpack(">H", data[sub:sub + 2])[0]
        if fmt == 4:
            seg_x2 = struct.unpack(">H", data[sub + 6:sub + 8])[0]
            seg = seg_x2 // 2
            ends = struct.unpack(f">{seg}H", data[sub + 14:sub + 14 + seg_x2])
            starts = struct.unpack(f">{seg}H", data[sub + 16 + seg_x2:sub + 16 + 2 * seg_x2])
            for start, end in zip(starts, ends):
                if start != 0xFFFF:
                    codepoints.update(range(start, end + 1))
        elif fmt == 12:
            group_count = struct.unpack(">I", data[sub + 12:sub + 16])[0]
            for g in range(group_count):
                start, end, _ = struct.unpack(">III", data[sub + 16 + 12 * g:sub + 28 + 12 * g])
                codepoints.update(range(start, end + 1))
    return codepoints


def macro_name(icon_name):
    return "ICON_LC_" + re.sub(r"[^A-Z0-9]", "_", icon_name.upper())


def utf8_literal(codepoint):
    return "".join(f"\\x{byte:02x}" for byte in chr(codepoint).encode("utf-8"))


def main():
    if len(sys.argv) not in (3, 4):
        raise SystemExit(__doc__)

    font_dir = Path(sys.argv[1])
    version = sys.argv[2]
    output = Path(sys.argv[3]) if len(sys.argv) == 4 else DEFAULT_OUTPUT

    mapping = json.loads((font_dir / "codepoints.json").read_text(encoding="utf-8"))
    present = read_cmap(font_dir / "lucide.ttf")

    # The font also maps a few ASCII glyphs; only private use area icons belong in the header
    icons = {}
    for name, codepoint in mapping.items():
        if codepoint < 0xE000 or codepoint not in present:
            continue
        macro = macro_name(name)
        if macro in icons and icons[macro] != codepoint:
            raise SystemExit(f"macro collision: {macro} maps to two codepoints")
        icons[macro] = codepoint

    if not icons:
        raise SystemExit("no icons found")

    lo = min(icons.values())
    hi = max(icons.values())

    lines = [
        "// Generated by Tools/generate_editor_icons.py - do not edit by hand.",
        f"// Lucide {version} (https://github.com/lucide-icons/lucide), font lucide.ttf, ISC license.",
        "",
        "#pragma once",
        "",
        '#define FONT_ICON_FILE_NAME_LC "lucide.ttf"',
        f'#define LUCIDE_VERSION "{version}"',
        "",
        f"#define ICON_MIN_LC 0x{lo:04x}",
        f"#define ICON_MAX_16_LC 0x{hi:04x}",
        f"#define ICON_MAX_LC 0x{hi:04x}",
        "",
    ]
    for macro in sorted(icons):
        codepoint = icons[macro]
        lines.append(f'#define {macro} "{utf8_literal(codepoint)}"\t// U+{codepoint:04x}')

    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{output}: {len(icons)} icons, U+{lo:04x}..U+{hi:04x}")


if __name__ == "__main__":
    main()
